// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA21SgjBvwz2O7sYsqGs6oXQj65V1DLkTk',
    appId: '1:671718312680:web:2403d39eab177785f9d75d',
    messagingSenderId: '671718312680',
    projectId: 'sheride-48cbf',
    authDomain: 'sheride-48cbf.firebaseapp.com',
    storageBucket: 'sheride-48cbf.firebasestorage.app',
    measurementId: 'G-BP83FP07GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKjDIwnhAiHxitrKFTKqN_O7YT5LsvLxM',
    appId: '1:671718312680:android:1a76b4b0fe982ce5f9d75d',
    messagingSenderId: '671718312680',
    projectId: 'sheride-48cbf',
    storageBucket: 'sheride-48cbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKzLbTgxesq8GlHFqhKTW2BB8L2z0E4As',
    appId: '1:671718312680:ios:3a6eebb3fbe4f206f9d75d',
    messagingSenderId: '671718312680',
    projectId: 'sheride-48cbf',
    storageBucket: 'sheride-48cbf.firebasestorage.app',
    iosBundleId: 'com.example.sheride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKzLbTgxesq8GlHFqhKTW2BB8L2z0E4As',
    appId: '1:671718312680:ios:3a6eebb3fbe4f206f9d75d',
    messagingSenderId: '671718312680',
    projectId: 'sheride-48cbf',
    storageBucket: 'sheride-48cbf.firebasestorage.app',
    iosBundleId: 'com.example.sheride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA21SgjBvwz2O7sYsqGs6oXQj65V1DLkTk',
    appId: '1:671718312680:web:8d73710a17e1e6b4f9d75d',
    messagingSenderId: '671718312680',
    projectId: 'sheride-48cbf',
    authDomain: 'sheride-48cbf.firebaseapp.com',
    storageBucket: 'sheride-48cbf.firebasestorage.app',
    measurementId: 'G-R0KQNZ8ND0',
  );
}
